version: "3"

services:
  traefik:
    image: traefik
    container_name: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./log:/log
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.traefik_dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik_dashboard.service=api@internal"
